name: Supabase Keep Alive + Slack

on:
  schedule:
    - cron: "0 0 */2 * *" # every 2 days à minuit UTC
  workflow_dispatch: # permet déclenchement manuel

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Installer Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      # 3️⃣ Installer dépendances
      - name: Install dependencies
        run: go mod tidy

      # 4️⃣ Ping Supabase
      - name: Ping Supabase
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: go run main.go
